config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  passwordless_for :auth

  resources :users do
    member do
      get   "password", action: "edit_password"
      put   "password", action: "update_password"
      patch "password", action: "update_password"
    end
  end
  resources :groups
end

app/models/group.rb
class Group < ActiveLdap::Base
  include ActiveModel::Model
  ldap_mapping dn_attribute: 'cn', prefix: 'ou=groups', classes: ['posixGroup', 'groupOfUniqueNames']

  has_many :users, class_name: 'User', wrap: 'uniqueMember', primary_key: 'dn'
  has_many :primary_users, class_name: 'User', foreign_key: 'gidNumber', primary_key: 'gidNumber'

  after_create do
    Serial.increment_gid
  end

  def self.admins
    unless group = Group.first('admins')
      group = Group.new
      group.update_attributes(cn: 'admins', gid_number: Serial.next_gid)
    end
    return group
  end

  def self.users
    unless group = Group.first('users')
      group = Group.new
      group.update_attributes(cn: 'users', gid_number:  Serial.next_gid)
    end
    return group
  end

  def append(user)
    return if self.include?(user)

    members = self.unique_member(true)
    members.append(user.dn.to_s)
    self.unique_member = members

    self.save!
  end

  def remove(user)
    return unless self.include?(user)

    members = self.unique_member(true)
    members.delete(user.dn.to_s)
    self.unique_member = members

    self.save!
  end

  def include?(user)
    members = self.unique_member(true)
    members.include?(user.dn.to_s)
  end

  def destroy
    self.delete_all
  end

  def to_param
    gid_number.to_s
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_session!
  before_action :set_group, only: %i[ show edit update destroy ]

  rescue_from Pundit::NotDefinedError, with: :not_authorized
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  # GET /groups or /groups.json
  def index
    authorize Group
    @groups = Group.all#.order(gid_number: 'asc')
  end

  # GET /groups/1 or /groups/1.json
  def show
    authorize Group
    respond_to do |format|
      format.html { redirect_to edit_group_path(@group) }
      format.json { render :show, status: :ok, location: @group }
    end
  end

  # GET /groups/new
  def new
    authorize Group
    @group = Group.new
    @group.assign_attributes(gid_number: Serial.next_gid)
  end

  # GET /groups/1/edit
  def edit
    authorize Group
  end

  # POST /groups or /groups.json
  def create
    authorize Group
    @group = Group.new
    @group.assign_attributes(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    authorize Group
    @group.assign_attributes(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    authorize Group
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(attribute: 'gidNumber', value: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params[:group][:uniqueMember] ||= []
      params.require(:group).permit(:cn, :gid_number, uniqueMember: [])
    end

    def not_authorized
      redirect_to user_path(current_user)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if notice then %>
  <div class='alert alert-primary alert-dismissible fade show mb-2'>
    <%= notice %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% if alert then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <%= alert %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% unless @group.errors.empty? then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <% @group.errors.full_messages.each do |message| %>
      <%= message %><br/>
    <% end %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>

<%= form_with(url: action, method: method) do |form| %>
  <div class='card mb-4'>
    <div class='card-header bg-transparent'>
      <div class='fs-4 mb-0'>
        <i class='bi bi-tag'></i>
        Group
      </div>
    </div>
    <ul class='list-group list-group-flush'>
      <li class='list-group-item'>
        <div class='row justify-content-between'>
          <div class='col-3 fs-6'><label class='form-label text-muted my-1'>name</label></div>
          <div class='col-9 fs-5'>
            <%= text_field(
              :group, :cn,
              class: "form-control#{'-plaintext' if !@group.new_entry? && (@group == Group.admins || @group == Group.users)} px-2 py-0",
              readonly: (!@group.new_entry? && (@group == Group.admins || @group == Group.users)),
            ) %>
          </div>
        </div>
      </li>
      <li class='list-group-item'>
        <div class='row justify-content-between'>
          <div class='col-3 fs-6'><label class='form-label text-muted my-1'>gid number</label></div>
          <div class='col-9 fs-5'>
            <%= text_field :group, :gid_number, class: 'form-control-plaintext px-2 py-0', readonly: true %>
          </div>
        </div>
      </li>
      <li class='list-group-item'>
        <div class='row justify-content-between'>
          <div class='col-3 fs-6'><label class='form-label text-muted my-1'>members</label></div>
          <div class='col-9'>
            <ul class='list-group'>
              <% User.all(order: 'asc').each do |user| %>
                <li class='list-group-item'>
                  <%= check_box :group, :uniqueMember, {multiple: true, checked: @group.include?(user), class: 'form-check-input me-2', disabled: (@group.cn.present? && @group == Group.users)}, user.dn, nil %>
                  <label class='form-check-label'>
                    <i class="bi bi-person"></i>
                    <%= user.uid %>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>

  <%= form.submit 'Submit group', class: 'btn btn-primary' %>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
</div>

app/views/groups/edit.html.erb
<%= render 'form', group: @group, action: group_path(@group), method: :patch %>

<div class='fs-4 mt-5'>
  <i class='bi bi-eraser'></i>
  Delete group
</div>
<p class='text-muted mb-0'>Once you delete your account, there's no way to recover it.</p>
<%= link_to(
  'Delete this group', group_path(@group),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete \"#{@group.cn}\" permanently?"},
  class: "btn btn-danger mt-2 #{'disabled' if @group == Group.admins || @group == Group.users}" ) %>

app/views/groups/index.html.erb
<% if notice then %>
  <div class='alert alert-primary alert-dismissible fade show mb-2'>
    <%= notice %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% if alert then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <%= alert %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>

<h1 class='h2 mb-3'>Groups</h1>
<div id='group' class='list-group'>
  <% @groups.each do |group| %>
    <%= link_to group_path(group), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-start' do %>
      <div class='fs-5 me-auto'>
        <i class='bi bi-tag me-1'></i>
        <span><%= group.cn %></span>
        <small class='fs-6 text-muted ms-1'><%= group.gid_number %></small>
      </div>
      <span class="badge bg-secondary rounded-pill"><%= group.users.size %> users</span>
    <% end %>
  <% end %>
</div>

<%= link_to 'Add new group', new_group_path, class: 'btn btn-primary mt-5' %>

app/views/groups/new.html.erb
<%= render 'form', group: @group, action: groups_path, method: :post %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>