config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  passwordless_for :auth

  resources :users do
    member do
      get   "password", action: "edit_password"
      put   "password", action: "update_password"
      patch "password", action: "update_password"
    end
  end
  resources :groups
end

app/models/user.rb
class User < ActiveLdap::Base
  include ActiveModel::Model
  ldap_mapping dn_attribute: 'uid', prefix: 'ou=users', classes: ['posixAccount', 'inetOrgPerson']

  belongs_to :groups, class_name: 'Group', many: 'uniqueMember', foreign_key: 'dn'
  belongs_to :primary_group, class_name: 'Group', foreign_key: 'gidNumber', primary_key: 'gidNumber'

  validates :user_password, presence: true, length: { minimum: 8 }, allow_nil: true, confirmation: true
  validates :user_password_confirmation, presence: true

  before_save do
    self.user_password = ActiveLdap::UserPassword.ssha(user_password) if user_password.present?
  end

  after_create do
    Serial.increment_uid

    Group.users.append(self)
    Group.admins.append(self) if User.count == 1
  end

  def belongs_to?(group)
    group = Group.first(cn: group)
    return !group.nil? && group.include?(self)
  end

  def destroy
    self.delete_all
  end

  def to_param
    uid_number.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_session!
  before_action :set_user, only: %i[ show edit update destroy edit_password update_password ]

  rescue_from Pundit::NotDefinedError, with: :not_authorized
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  # GET /users or /users.json
  def index
    return redirect_to new_user_path unless current_user

    authorize User
    @users = User.all#.order(uid_number: 'asc')
  end

  # GET /users/1 or /users/1.json
  def show
    authorize @user
    respond_to do |format|
      format.html { redirect_to edit_user_path(@user) }
      format.json { render :show, status: :ok, location: @user }
    end
  end

  # GET /users/new
  def new
    authorize User
    @user = User.new
    @user.assign_attributes(
      cn:   current_session.name,
      sn:   current_session.name,
      uid:  current_session.name,
      mail: current_session.mail,
      uid_number: Serial.next_uid,
      gid_number: Group.users.gid_number,
      home_directory: File.join('/', 'home', current_session.name),
    )
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users or /users.json
  def create
    authorize User
    @user = User.new
    @user.assign_attributes(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    authorize @user
    @user.assign_attributes(user_params.except('user_password', 'user_password_confirmation'))

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /user/1/password
  def edit_password
    authorize @user
  end

  # POST/PATCH/PUT /user/1/password
  def update_password
    authorize @user
    @user.assign_attributes(user_params.slice('user_password', 'user_password_confirmation'))

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User password was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit_password, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    authorize @user
    sign_out Auth
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(attribute: 'uidNumber', value: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:uid, :cn, :sn, :mail, :uid_number, :gid_number, :login_shell, :home_directory, :user_password, :user_password_confirmation)
    end

    def not_authorized
      redirect_to user_path(current_user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<% if notice then %>
  <div class='alert alert-primary alert-dismissible fade show mb-2'>
    <%= notice %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% if alert then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <%= alert %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% unless @user.errors.empty? then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <% @user.errors.full_messages.each do |message| %>
      <%= message %><br/>
    <% end %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>

<div class='card mb-4'>
  <div class='card-header bg-transparent'>
    <div class='fs-4 mb-0'>
      <i class='bi bi-person'></i>
      User
    </div>
  </div>
  <ul class='list-group list-group-flush'>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>name</div></div>
        <div class='col-9 fs-5'><%= @user.uid %></div>
      </div>
    </li>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>mail address</div></div>
        <div class='col-9 fs-5'><%= @user.mail %></div>
      </div>
    </li>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>uid number</div></div>
        <div class='col-9 fs-5'><%= @user.uid_number %></div>
      </div>
    </li>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>gid number</div></div>
        <div class='col-9 fs-5'><%= @user.gid_number %></div>
      </div>
    </li>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>groups</div></div>
        <div class='col-9 fs-5'>
          <% @user.groups.each do |group| %>
            <span class='badge text-dark border'>
              <% if @user.gid_number == group.gid_number %>
                <i class="bi bi-tag-fill"></i>
              <% else %>
                <i class="bi bi-tag"></i>
              <% end %>
              <%= group.cn %>
            </span>
          <% end %>
        </div>
      </div>
    </li>
    <% if false %>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>login shell</div></div>
        <div class='col-9 fs-5'><%= @user.login_shell %></div>
      </div>
    </li>
    <li class='list-group-item'>
      <div class='row justify-content-between'>
        <div class='col-3 fs-6'><div class='text-muted my-1'>home directory</div></div>
        <div class='col-9 fs-5'><%= @user.home_directory %></div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<% if current_user == @user %>
  <div class='fs-4 mt-5'>
    <i class='bi bi-key'></i>
    Change password
  </div>
  <%= link_to 'Change password', password_user_path(@user), class: 'btn btn-primary mt-2' %>
<% end %>

<div class='fs-4 mt-5'>
  <i class='bi bi-eraser'></i>
  Delete account
</div>
<p class='text-muted mb-0'>Once you delete your account, there's no way to recover it.</p>
<%= link_to(
  'Delete this account', user_path(@user),
  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete \"#{@user.uid}\" permanently?" },
  class: "btn btn-danger mt-2" ) %>

app/views/users/edit_password.html.erb
<% if notice then %>
  <div class='alert alert-primary alert-dismissible fade show mb-2'>
    <%= notice %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% if alert then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <%= alert %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% unless @user.errors.empty? then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <% @user.errors.full_messages.each do |message| %>
      <%= message %><br/>
    <% end %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>

<p class='fs-5'> Please provide a new password for your <strong><%= current_session.mail %></strong> account.</p>
<%= form_with(method: :put, url: password_user_path(@user)) do |form| %>

  <div class='card mb-4'>
    <div class='card-header bg-transparent'>
      <div class='fs-4 mb-0'>
        <i class='bi bi-key'></i>
        Password
      </div>
    </div>
    <div class='card-body'>
      <div class='col-auto px-3'>
        <div class='form-group mb-3'>
          <label>New password</label>
          <%= password_field :user, :user_password, class: 'form-control' %>
        </div>
      </div>
      <div class='col-auto px-3'>
        <div class='form-group mb-3'>
          <label>Confirm password</label>
          <%= password_field :user, :user_password_confirmation, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class='col-auto'>
    <%= form.submit 'Update password', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if notice then %>
  <div class='alert alert-primary alert-dismissible fade show mb-2'>
    <%= notice %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% if alert then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <%= alert %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>

<h1 class='h2 mb-3'>Users</h1>
<div id="users" class='list-group'>
  <% @users.each do |user| %>
    <%= link_to user_path(user), class: 'list-group-item list-group-item-action d-flex justify-content-between' do %>
      <div class='fs-5'>
        <i class='bi bi-person me-1'></i>
        <span><%= user.uid %></span>
        <% if current_user.uid_number == user.uid_number %>
          <small>(you)</small>
        <% end%>
        <small class='fs-6 text-muted ms-1'><%= user.uid_number %></small>
      </div>
      <div>
        <% user.groups.each do |group| %>
          <span class='badge text-dark border ms-1'>
            <% if user.gid_number == group.gid_number %>
              <i class="bi bi-tag-fill"></i>
            <% else %>
              <i class="bi bi-tag"></i>
            <% end %>
            <%= group.cn %>
          </span>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<% if notice then %>
  <div class='alert alert-primary alert-dismissible fade show mb-2'>
    <%= notice %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% if alert then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <%= alert %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>
<% unless @user.errors.empty? then %>
  <div class='alert alert-danger alert-dismissible fade show mb-2'>
    <% @user.errors.full_messages.each do |message| %>
      <%= message %><br/>
    <% end %>
    <button type='button' class='btn-close' data-bs-dismiss='alert'></button>
  </div>
<% end %>

<p class='fs-5'> Please provide a new password for your <strong><%= current_session.mail %></strong> account.</p>
<%= form_with(url: users_path, method: :post) do |form| %>
  <%= hidden_field :user, :cn %>
  <%= hidden_field :user, :sn %>
  <%= hidden_field :user, :uid  %>
  <%= hidden_field :user, :mail %>
  <%= hidden_field :user, :uid_number %>
  <%= hidden_field :user, :gid_number %>
  <%= hidden_field :user, :home_directory %>
  <div class='card mb-4'>
    <div class='card-header bg-transparent'>
      <div class='fs-4 mb-0'>
        <i class='bi bi-key'></i>
        Password
      </div>
    </div>
    <div class='card-body'>
      <div class='col-auto px-3'>
        <div class='form-group mb-3'>
          <label>New password</label>
          <%= password_field :user, :user_password, class: 'form-control' %>
        </div>
      </div>
      <div class='col-auto px-3'>
        <div class='form-group mb-3'>
          <label>Confirm password</label>
          <%= password_field :user, :user_password_confirmation, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class='col-auto'>
    <%= form.submit 'Create your account', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>